### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by xcgfth** [rjk-git/bert_transformer_en2zh#1]
Why do you use the pre-trained word embedding of bert as the output of transformer?
Actually, I want to make the the pre-trained word embedding of bert as the input of transformer. In this way, the context embedding processed by the transformer as an encoder can be used as others applications.

**Comment by rjk-git** [comment]
I am a bit confused, what do you mean as the output of Transformer, is the output of Transformer-Decoder? In fact, I am using the pre-trained word embedding of bert as the Transformer-Encoder's output. As you say,  the context embedding processed by the transformer is completely a replacement for Transformer-Encoder in my project.
